//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHubClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHubClient.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bigger text.
        /// </summary>
        public static string AppBarBiggerText {
            get {
                return ResourceManager.GetString("AppBarBiggerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string AppBarLogOut {
            get {
                return ResourceManager.GetString("AppBarLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string AppBarRefresh {
            get {
                return ResourceManager.GetString("AppBarRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smaller text.
        /// </summary>
        public static string AppBarSmallerText {
            get {
                return ResourceManager.GetString("AppBarSmallerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string CommitPageAuthor {
            get {
                return ResourceManager.GetString("CommitPageAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string CommitPageDate {
            get {
                return ResourceManager.GetString("CommitPageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string CommitPageDetails {
            get {
                return ResourceManager.GetString("CommitPageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string CommitPageEmail {
            get {
                return ResourceManager.GetString("CommitPageEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        public static string CommitPageFiles {
            get {
                return ResourceManager.GetString("CommitPageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA.
        /// </summary>
        public static string CommitPageSHA {
            get {
                return ResourceManager.GetString("CommitPageSHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the file &quot;{0}&quot;. Please check your Internet connection..
        /// </summary>
        public static string ContentFileErrorMessage {
            get {
                return ResourceManager.GetString("ContentFileErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorMessageCaption {
            get {
                return ResourceManager.GetString("ErrorMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your GitHub username and password to gain access to your repositories..
        /// </summary>
        public static string LoginPageHint {
            get {
                return ResourceManager.GetString("LoginPageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided credentials are invalid..
        /// </summary>
        public static string LoginPageInvalidCredentials {
            get {
                return ResourceManager.GetString("LoginPageInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        public static string LoginPageLogin {
            get {
                return ResourceManager.GetString("LoginPageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to GitHub. Please make sure you&apos;re connected to the Internet..
        /// </summary>
        public static string LoginPageNoConnection {
            get {
                return ResourceManager.GetString("LoginPageNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a password..
        /// </summary>
        public static string LoginPageNoPassword {
            get {
                return ResourceManager.GetString("LoginPageNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a user name..
        /// </summary>
        public static string LoginPageNoUserName {
            get {
                return ResourceManager.GetString("LoginPageNoUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPagePassword {
            get {
                return ResourceManager.GetString("LoginPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GITHUB VIEWER.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred while authenticating your credentials with GitHub. Please try again later..
        /// </summary>
        public static string LoginPageUnkownError {
            get {
                return ResourceManager.GetString("LoginPageUnkownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string LoginPageUserName {
            get {
                return ResourceManager.GetString("LoginPageUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to branches.
        /// </summary>
        public static string RepoDetailsBranches {
            get {
                return ResourceManager.GetString("RepoDetailsBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commits.
        /// </summary>
        public static string RepoDetailsCommits {
            get {
                return ResourceManager.GetString("RepoDetailsCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while opening the directory &quot;{0}&quot;. Please check your Internet connection..
        /// </summary>
        public static string RepoDetailsDirectoryErrorMessage {
            get {
                return ResourceManager.GetString("RepoDetailsDirectoryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving the repository &quot;{0}&quot;. Please check your Internet connection..
        /// </summary>
        public static string RepoDetailsErrorMessage {
            get {
                return ResourceManager.GetString("RepoDetailsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        public static string RepoDetailsFiles {
            get {
                return ResourceManager.GetString("RepoDetailsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all repositories.
        /// </summary>
        public static string ReposAllRepositories {
            get {
                return ResourceManager.GetString("ReposAllRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch repositories. Please make sure you&apos;re connected to the Internet..
        /// </summary>
        public static string ReposErrorMessage {
            get {
                return ResourceManager.GetString("ReposErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forks.
        /// </summary>
        public static string ReposForks {
            get {
                return ResourceManager.GetString("ReposForks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private.
        /// </summary>
        public static string ReposPrivate {
            get {
                return ResourceManager.GetString("ReposPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public.
        /// </summary>
        public static string ReposPublic {
            get {
                return ResourceManager.GetString("ReposPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GITHUB VIEWER | {0}.
        /// </summary>
        public static string ReposTitle {
            get {
                return ResourceManager.GetString("ReposTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
